version: "3.5"
services:
    nnd-exporter:
        image: fargus3222/nnd-exporter
        restart: unless-stopped
        ports:
          - "8082:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - CONTAINER_ID=${CONTAINER_ID}
